name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ 'AKIASBILANF7ZILZBYMV' }}
          aws-secret-access-key: ${{ '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' }}
          aws-region: ${{ 'ap-south-1' }}

      - name: Terraform init and apply
        run: |
          terraform init
          terraform apply -auto-approve

      - name: Deploy to ECS
        run: |
          aws ecs update-service --cluster medusa-ecs-cluster --service medusa-backend-service --task-definition medusa-backend-task

